### ISSUE TITLE
Suggestion/Feature Request: Change keyboard mapping in build.yml before building

### ISSUE THREAD

**Issue by 0xDedSec42** [lkarlslund/deploy-goad#3]
In the `build.yml` the keyboard layout is being set to fr-FR. I'd suggest to have this changed interactively by your script.

The same goes for the amount of RAM and CPUs used by the machines. I think these are the only variables that probably need changing before running the whole building process.

**Comment by lkarlslund** [comment]
It's a nice idea and I agree.

**Comment by lkarlslund** [comment]
Implemented custom keyboard support in fork of GOAD with settings.ini file
