### ISSUE TITLE
issue on installation 

### ISSUE THREAD

**Issue by isarabia92** [lkarlslund/deploy-goad#4]
Hello,

Thank you for your awesome script.After running i encountered this error:

%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/root/.vagrant.d/boxes/StefanScherer-VAGRANTSLASH-windows_2019/2021.05.15/virtualbox/box.ovf", "--vsys", "0", "--vmname", "WindowsServer2019_1660618847225_24293", "--vsys", "0", "--unit", "10", "--disk", "/root/VirtualBox VMs/WindowsServer2019_1660618847225_24293/WindowsServer2019-disk001.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /root/.vagrant.d/boxes/StefanScherer-VAGRANTSLASH-windows_2019/2021.05.15/virtualbox/box.ovf...

I wonder if you know how to solve this issue.

**Comment by lkarlslund** [comment]
I'm not sure, there is no error message. I'd check for disk space issues and look for a VirtualBox log file. Sorry, can't really help you any more than that.
