### ISSUE TITLE
errors during setup

### ISSUE THREAD

**Issue by ll3N1GmAll** [lkarlslund/deploy-goad#5]
Here are the errors I get when running deploy-goad:

command:
vagrant plugin install winrm

Error:
Installing the 'winrm' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

command:
vagrant plugin install winrm-elevated

Error:
Installing the 'winrm-elevated' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

**Comment by lkarlslund** [comment]
Lots of changes to GOAD since then, please retry with new version
