### ISSUE TITLE
Starting DC01 fails, times out

### ISSUE THREAD

**Issue by Ondjultomte** [lkarlslund/deploy-goad#6]
Im running a ubuntu vm in proxmox, with nested enabled.

==> GOAD-DC01: Waiting for machine to boot. This may take a few minutes...
    GOAD-DC01: WinRM address: 127.0.0.1:55985
    GOAD-DC01: WinRM username: vagrant
    GOAD-DC01: WinRM execution_time_limit: PT2H
    GOAD-DC01: WinRM transport: negotiate

this times out.
how can I debug this issue?

**Comment by Ondjultomte** [comment]
I rebooted and ran the script again, now it progresses further.

**Comment by Ondjultomte** [comment]
NowI come this fasr
`==> GOAD-DC01: Checking for guest additions in VM...
==> GOAD-DC01: Configuring and enabling network interfaces...
==> GOAD-DC01: Running provisioner: shell...
    GOAD-DC01: Running: ../../../../vagrant/Install-WMF3Hotfix.ps1 as C:\tmp\vagrant-shell.ps1
==> GOAD-DC01: Running provisioner: shell...
    GOAD-DC01: Running: ../../../../vagrant/ConfigureRemotingForAnsible.ps1 as C:\tmp\vagrant-shell.ps1
    GOAD-DC01: Self-signed SSL certificate generated; thumbprint: 2D5AE8F16E5083396F221DAAA7A9432F9D59665F
    GOAD-DC01: 
    GOAD-DC01: 
    GOAD-DC01: wxf                 : http://schemas.xmlsoap.org/ws/2004/09/transfer
    GOAD-DC01: a                   : http://schemas.xmlsoap.org/ws/2004/08/addressing
    GOAD-DC01: w                   : http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
    GOAD-DC01: lang                : en-US
    GOAD-DC01: Address             : http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
    GOAD-DC01: ReferenceParameters : ReferenceParameters
    GOAD-DC01: 
    GOAD-DC01: Ok.
    GOAD-DC01: 
    GOAD-DC01: 
    GOAD-DC01: 
==> GOAD-DC02: Importing base box 'StefanScherer/windows_2019'...
==> GOAD-DC02: Matching MAC address for NAT networking...
==> GOAD-DC02: Checking if box 'StefanScherer/windows_2019' version '2021.05.15' is up to date...
==> GOAD-DC02: Setting the name of the VM: GOAD-DC02
==> GOAD-DC02: Fixed port collision for 5985 => 55985. Now on port 2200.
==> GOAD-DC02: Fixed port collision for 5986 => 55986. Now on port 2201.
==> GOAD-DC02: Fixed port collision for 22 => 2222. Now on port 2202.
==> GOAD-DC02: Clearing any previously set network interfaces...
==> GOAD-DC02: Preparing network interfaces based on configuration...
    GOAD-DC02: Adapter 1: nat
    GOAD-DC02: Adapter 2: hostonly
==> GOAD-DC02: Forwarding ports...
    GOAD-DC02: 5985 (guest) => 2200 (host) (adapter 1)
    GOAD-DC02: 5986 (guest) => 2201 (host) (adapter 1)
    GOAD-DC02: 22 (guest) => 2202 (host) (adapter 1)
==> GOAD-DC02: Running 'pre-boot' VM customizations...
==> GOAD-DC02: Booting VM...
==> GOAD-DC02: Waiting for machine to boot. This may take a few minutes...
    GOAD-DC02: WinRM address: 127.0.0.1:2200
    GOAD-DC02: WinRM username: vagrant
    GOAD-DC02: WinRM execution_time_limit: PT2H
    GOAD-DC02: WinRM transport: negotiate
`

and again it seems to timeout.

I noticed that eachtime it timesout the memory allocation sky rockets and reach the limit 32GB, I will increase it to 64GB in my next reboot.

<img width="1078" alt="image" src="https://github.com/lkarlslund/deploy-goad/assets/16661547/6f8826ec-9ffa-4d23-88f1-4b346d9200aa">

**Comment by Ondjultomte** [comment]
adding more memory doesnt help, 

  GOAD-DC01: WinRM username: vagrant
    GOAD-DC01: WinRM execution_time_limit: PT2H
    GOAD-DC01: WinRM transport: negotiate
==> GOAD-DC01: Machine booted and ready!
==> GOAD-DC01: Checking for guest additions in VM...
==> GOAD-DC01: Configuring and enabling network interfaces...
==> GOAD-DC01: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> GOAD-DC01: flag to force provisioning. Provisioners marked to run always will still run.
==> GOAD-DC02: Checking if box 'StefanScherer/windows_2019' version '2021.05.15' is up to date...
==> GOAD-DC02: Clearing any previously set forwarded ports...
==> GOAD-DC02: Fixed port collision for 5985 => 55985. Now on port 2200.
==> GOAD-DC02: Fixed port collision for 5986 => 55986. Now on port 2201.
==> GOAD-DC02: Fixed port collision for 22 => 2222. Now on port 2202.
==> GOAD-DC02: Clearing any previously set network interfaces...
==> GOAD-DC02: Preparing network interfaces based on configuration...
    GOAD-DC02: Adapter 1: nat
    GOAD-DC02: Adapter 2: hostonly
==> GOAD-DC02: Forwarding ports...
    GOAD-DC02: 5985 (guest) => 2200 (host) (adapter 1)
    GOAD-DC02: 5986 (guest) => 2201 (host) (adapter 1)
    GOAD-DC02: 22 (guest) => 2202 (host) (adapter 1)
==> GOAD-DC02: Running 'pre-boot' VM customizations...
==> GOAD-DC02: Booting VM...
==> GOAD-DC02: Waiting for machine to boot. This may take a few minutes...
    GOAD-DC02: WinRM address: 127.0.0.1:2200
    GOAD-DC02: WinRM username: vagrant
    GOAD-DC02: WinRM execution_time_limit: PT2H
    GOAD-DC02: WinRM transport: negotiate
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
/opt/goad
[!] vagrant finish with error abort
Deployment failed

**Comment by Ondjultomte** [comment]
I think its the timeout that needs to be increased as stated . but in which file located where should it be changed ?

**Comment by tpmiller87** [comment]
@Ondjultomte I'm attempting to deploy this on an Ubuntu server image hosted on XCP-ng and I get to the same spot. Instead of the script failing, however, my Ubuntu VM crashes and reboots every time. Have you figured out a solution?

**Comment by lkarlslund** [comment]
Sorry, I really can't help you there. I've only tested my script on a real host machine, not with nested virtualization (I gave up on that, due to similar problems with VirtualBox being way too slow to be usable)

**Comment by lkarlslund** [comment]
Closing this due to nested virtualization being used, which I've specifically given up on, due to the terrible performance VirtualBox offers when doing that.
